language: ruby
rvm:
  - 2.1.2
  - 2.2.3
  - 2.3.0

env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.1.4"
  - "RAILS_VERSION=4.2.5"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: 2.1.2
